import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/providers";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KISAN",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <SessionProvider session={session}>
          <StoreProvider>
            <div className="w-full">
              {children}
            </div>
          </StoreProvider>
        </SessionProvider>
        <NextTopLoader shadow={false} showSpinner={false} color="blue" />
      </body>
    </html>
  );
}
